package md.victordov.lab.vo;

import java.util.HashSet;

import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student", catalog = "uni2_4t")
public class Student implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	public Student() {
	}

	public Integer getSId() {
		return this.SId;
	}

	public void setSId(Integer SId) {
		this.SId = SId;
	}
	
	
	public String getNume() {
		return this.nume;
	}

	public void setNume(String nume) {
		this.nume = nume;
	}
	
	
	public String getPrenume() {
		return this.prenume;
	}

	public void setPrenume(String prenume) {
		this.prenume = prenume;
	}
	
	
	public String getGrupa() {
		return this.grupa;
	}

	public void setGrupa(String grupa) {
		this.grupa = grupa;
	}
	
	
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	
	
	public String getTelFix() {
		return this.telFix;
	}

	public void setTelFix(String telFix) {
		this.telFix = telFix;
	}

	public Set<StudCurs> getStudCurses() {
		return this.studCurses;
	}

	public void setStudCurses(Set<StudCurs> studCurses) {
		this.studCurses = studCurses;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "s_id", unique = true, nullable = false)
	private Integer SId;

	@Column(name = "nume", nullable = true, length = 30)
	private String nume;

	@Column(name = "prenume", nullable = false, length = 30)
	private String prenume;

	@Column(name = "grupa", nullable = false, length = 15)
	private String grupa;

	@Column(name = "email", nullable = false, length = 30)
	private String email;

	@Column(name = "telFix", nullable = false, length = 20)
	private String telFix;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "student")
	private Set<StudCurs> studCurses = new HashSet<StudCurs>(0);

}